/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/weapon-properties": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a paginated list of weapon properties */
        get: operations["getWeaponProperties"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/weapon-properties/{index}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a weapon property by index */
        get: operations["getWeaponProperty"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/traits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a paginated list of traits */
        get: operations["getTraits"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/traits/{index}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a trait by index */
        get: operations["getTrait"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subraces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a paginated list of subraces */
        get: operations["getSubraces"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subraces/{index}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a subrace by index */
        get: operations["getSubrace"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subclasses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a paginated list of subclasses */
        get: operations["getSubclasses"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subclasses/{index}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a subclass by index */
        get: operations["getSubclass"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/spells": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a paginated list of spells */
        get: operations["getSpells"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/spells/{index}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a spell by index */
        get: operations["getSpell"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a paginated list of skills */
        get: operations["getSkills"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skills/{index}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a skill by index */
        get: operations["getSkill"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a paginated list of rules */
        get: operations["getRules"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rules/{index}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a rule by index */
        get: operations["getRule"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rule-sections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a paginated list of rule sections */
        get: operations["getRuleSections"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rule-sections/{index}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a rule section by index */
        get: operations["getRuleSection"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/races": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a paginated list of races */
        get: operations["getRaces"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/races/{index}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a race by index */
        get: operations["getRace"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/proficiencies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a paginated list of proficiencies */
        get: operations["getProficiencies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/proficiencies/{index}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a proficiency by index */
        get: operations["getProficiency"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/monsters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a paginated list of monsters */
        get: operations["getMonsters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/monsters/{index}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a monster by index */
        get: operations["getMonster"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/magic-schools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a paginated list of magic schools */
        get: operations["getMagicSchools"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/magic-schools/{index}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a magic school by index */
        get: operations["getMagicSchool"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/magic-items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a paginated list of magic items */
        get: operations["getMagicItems"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/magic-items/{index}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a magic item by index */
        get: operations["getMagicItem"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/levels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a paginated list of levels */
        get: operations["getLevels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/levels/{index}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a level by index */
        get: operations["getLevel"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/languages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a paginated list of languages */
        get: operations["getLanguages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/languages/{index}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a language by index */
        get: operations["getLanguage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/features": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a paginated list of features */
        get: operations["getFeatures"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/features/{index}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a feature by index */
        get: operations["getFeature"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a paginated list of feats */
        get: operations["getFeats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feats/{index}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a feat by index */
        get: operations["getFeat"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/equipment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a paginated list of equipment */
        get: operations["getAllEquipment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/equipment/{index}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get equipment by index */
        get: operations["getEquipment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/equipment-categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a paginated list of equipment categories */
        get: operations["getEquipmentCategories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/equipment-categories/{index}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an equipment category by index */
        get: operations["getEquipmentCategory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/damage-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a paginated list of damage types */
        get: operations["getDamageTypes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/damage-types/{index}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a damage type by index */
        get: operations["getDamageType"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conditions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a paginated list of conditions */
        get: operations["getConditions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conditions/{index}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a condition by index */
        get: operations["getCondition"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/classes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a paginated list of character classes */
        get: operations["getClasses"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/classes/{index}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a character class by index */
        get: operations["getCharacterClass"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backgrounds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a paginated list of backgrounds */
        get: operations["getBackgrounds"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backgrounds/{index}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a background by index */
        get: operations["getBackground"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alignments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a paginated list of alignments */
        get: operations["getAlignments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alignments/{index}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an alignment by index */
        get: operations["getAlignment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ability-scores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a paginated list of ability scores */
        get: operations["getAbilityScores"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ability-scores/{index}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an ability score by index */
        get: operations["getAbilityScore"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Page: {
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            sort?: string[];
        };
        PagedModelWeaponPropertyView: {
            content: components["schemas"]["WeaponPropertyView"][];
            page: components["schemas"]["Page"];
        };
        WeaponPropertyView: {
            desc: string[];
            index: string;
            name: string;
            url: string;
        };
        AbilityBonusOption: WithRequired<components["schemas"]["Option"], "optionType"> & {
            abilityScore: components["schemas"]["ApiReference"];
            /** Format: int32 */
            bonus: number;
        };
        ActionDamage: {
            damageType: components["schemas"]["ApiReference"];
            damageAtCharacterLevel: {
                [key: string]: string;
            };
        };
        ActionOption: WithRequired<components["schemas"]["Option"], "optionType"> & {
            actionName: string;
            /** Format: int32 */
            count: number;
            /** @enum {string} */
            type: "melee" | "ranged" | "ability" | "magic";
            notes?: string;
        };
        ApiReference: {
            index?: string;
            name?: string;
            url?: string;
        };
        AreaOfEffect: {
            /** Format: int32 */
            size: number;
            /** @enum {string} */
            type: "sphere" | "cube" | "cylinder" | "line" | "cone" | "unknown";
        };
        BreathOption: WithRequired<components["schemas"]["Option"], "optionType"> & {
            name: string;
            dt?: components["schemas"]["DifficultyClass"];
            damage?: components["schemas"]["Damage"][];
        };
        Choice: {
            desc?: string;
            /** Format: int32 */
            choose: number;
            type: string;
            from: components["schemas"]["EquipmentCategoryOptionSet"] | components["schemas"]["OptionsArrayOptionSet"] | components["schemas"]["ResourceListOptionSet"];
        };
        ChoiceOption: WithRequired<components["schemas"]["Option"], "optionType"> & {
            choice: components["schemas"]["Choice"];
        };
        CountedReferenceOption: WithRequired<components["schemas"]["Option"], "optionType"> & {
            /** Format: int32 */
            count: number;
            of: components["schemas"]["ApiReference"];
            prerequisites?: (components["schemas"]["FeaturePrerequisite"] | components["schemas"]["LevelPrerequisite"] | components["schemas"]["ProficiencyPrerequisite"] | components["schemas"]["SpellPrerequisite"])[];
        };
        Damage: {
            damageDice?: string;
            damageType?: components["schemas"]["ApiReference"];
        };
        DamageOption: WithRequired<components["schemas"]["Option"], "optionType"> & {
            damageType: components["schemas"]["ApiReference"];
            damageDice: string;
            notes: string;
        };
        DifficultyClass: {
            dcType: components["schemas"]["ApiReference"];
            /** Format: int32 */
            dcValue?: number;
            /** @enum {string} */
            successType: "none" | "half" | "other";
        };
        EquipmentCategoryOptionSet: WithRequired<components["schemas"]["OptionSet"], "optionSetType"> & {
            equipmentCategory: components["schemas"]["ApiReference"];
        };
        FeaturePrerequisite: WithRequired<components["schemas"]["Prerequisite"], "type"> & {
            feature: string;
        };
        IdealOption: WithRequired<components["schemas"]["Option"], "optionType"> & {
            desc: string;
            alignments: components["schemas"]["ApiReference"][];
        };
        LevelPrerequisite: WithRequired<components["schemas"]["Prerequisite"], "type"> & {
            /** Format: int32 */
            level: number;
        };
        MultipleOption: WithRequired<components["schemas"]["Option"], "optionType"> & {
            items: (components["schemas"]["AbilityBonusOption"] | components["schemas"]["ActionOption"] | components["schemas"]["BreathOption"] | components["schemas"]["ChoiceOption"] | components["schemas"]["CountedReferenceOption"] | components["schemas"]["DamageOption"] | components["schemas"]["IdealOption"] | components["schemas"]["MultipleOption"] | components["schemas"]["ReferenceOption"] | components["schemas"]["ScorePrerequisiteOption"] | components["schemas"]["StringOption"])[];
        };
        Option: {
            optionType: string;
        };
        OptionSet: {
            optionSetType: string;
        };
        OptionsArrayOptionSet: WithRequired<components["schemas"]["OptionSet"], "optionSetType"> & {
            options?: (components["schemas"]["AbilityBonusOption"] | components["schemas"]["ActionOption"] | components["schemas"]["BreathOption"] | components["schemas"]["ChoiceOption"] | components["schemas"]["CountedReferenceOption"] | components["schemas"]["DamageOption"] | components["schemas"]["IdealOption"] | components["schemas"]["MultipleOption"] | components["schemas"]["ReferenceOption"] | components["schemas"]["ScorePrerequisiteOption"] | components["schemas"]["StringOption"])[];
        };
        PagedModelTraitView: {
            content: components["schemas"]["TraitView"][];
            page: components["schemas"]["Page"];
        };
        Prerequisite: {
            type: string;
        };
        ProficiencyPrerequisite: WithRequired<components["schemas"]["Prerequisite"], "type"> & {
            proficiency?: components["schemas"]["ApiReference"];
        };
        ReferenceOption: WithRequired<components["schemas"]["Option"], "optionType"> & {
            item: components["schemas"]["ApiReference"];
        };
        ResourceListOptionSet: WithRequired<components["schemas"]["OptionSet"], "optionSetType"> & {
            resourceListUrl: string;
        };
        ScorePrerequisiteOption: WithRequired<components["schemas"]["Option"], "optionType"> & {
            abilityScore: components["schemas"]["ApiReference"];
            /** Format: int32 */
            minimumScore: number;
        };
        SpellPrerequisite: WithRequired<components["schemas"]["Prerequisite"], "type"> & {
            spell: string;
        };
        StringOption: WithRequired<components["schemas"]["Option"], "optionType"> & {
            string: string;
        };
        TraitProficiency: {
            index: string;
            name: string;
            url: string;
        };
        TraitSpecific: {
            subtraitOptions?: components["schemas"]["Choice"];
            spellOptions?: components["schemas"]["Choice"];
            damageType?: components["schemas"]["ApiReference"];
            breathWeapon?: components["schemas"]["TraitSpecificAction"];
        };
        TraitSpecificAction: {
            name: string;
            desc: string;
            usage: components["schemas"]["Usage"];
            dc: components["schemas"]["DifficultyClass"];
            damage: components["schemas"]["ActionDamage"][];
            areaOfEffect: components["schemas"]["AreaOfEffect"];
        };
        TraitView: {
            desc: string[];
            index: string;
            name: string;
            proficiencies?: components["schemas"]["TraitProficiency"][];
            proficiencyChoices?: components["schemas"]["Choice"];
            languageOptions?: components["schemas"]["Choice"];
            races: components["schemas"]["ApiReference"][];
            subraces: components["schemas"]["ApiReference"][];
            parent?: components["schemas"]["ApiReference"];
            traitSpecific?: components["schemas"]["TraitSpecific"];
            url: string;
        };
        Usage: {
            type: string;
            /** Format: int32 */
            times: number;
        };
        AbilityBonus: {
            abilityScore: components["schemas"]["ApiReference"];
            /** Format: int64 */
            bonus: number;
        };
        PagedModelSubraceView: {
            content: components["schemas"]["SubraceView"][];
            page: components["schemas"]["Page"];
        };
        SubraceView: {
            abilityBonuses: components["schemas"]["AbilityBonus"][];
            desc: string;
            index: string;
            languages?: components["schemas"]["ApiReference"][];
            languageOptions?: components["schemas"]["Choice"];
            name: string;
            race: components["schemas"]["ApiReference"];
            racialTraits: components["schemas"]["ApiReference"][];
            startingProficiencies?: components["schemas"]["ApiReference"][];
            url: string;
        };
        PagedModelSubclassView: {
            content: components["schemas"]["SubclassView"][];
            page: components["schemas"]["Page"];
        };
        Spell: WithRequired<components["schemas"]["MonsterArmorClass"], "type" | "value"> & {
            spell: components["schemas"]["ApiReference"];
        };
        SubclassView: {
            class: components["schemas"]["ApiReference"];
            desc: string[];
            index: string;
            name: string;
            spells?: components["schemas"]["Spell"][];
            subclassFlavor: string;
            subclassLevels: string;
            url: string;
        };
        PagedModelSpellView: {
            content: components["schemas"]["SpellView"][];
            page: components["schemas"]["Page"];
        };
        SpellDc: {
            dcType: components["schemas"]["ApiReference"];
            dcSuccess: string;
            desc?: string;
        };
        SpellView: {
            areaOfEffect?: components["schemas"]["AreaOfEffect"];
            attackType?: string;
            castingTime: string;
            classes: components["schemas"]["ApiReference"][];
            components: string[];
            concentration: boolean;
            damage?: components["schemas"]["Damage"];
            dc?: components["schemas"]["SpellDc"];
            desc: string[];
            duration: string;
            healAtSlotLevel?: {
                [key: string]: string;
            };
            higherLevel?: string[];
            index: string;
            /** Format: int32 */
            level: number;
            material?: string;
            name: string;
            range: string;
            ritual: boolean;
            school: components["schemas"]["ApiReference"];
            subclasses: components["schemas"]["ApiReference"][];
            url: string;
        };
        PagedModelSkillView: {
            content: components["schemas"]["SkillView"][];
            page: components["schemas"]["Page"];
        };
        SkillView: {
            abilityScore: components["schemas"]["ApiReference"];
            desc: string[];
            index: string;
            name: string;
            url: string;
        };
        PagedModelRuleView: {
            content: components["schemas"]["RuleView"][];
            page: components["schemas"]["Page"];
        };
        RuleView: {
            desc: string;
            index: string;
            name: string;
            subsections: components["schemas"]["ApiReference"][];
            url: string;
        };
        PagedModelRuleSectionView: {
            content: components["schemas"]["RuleSectionView"][];
            page: components["schemas"]["Page"];
        };
        RuleSectionView: {
            desc: string;
            index: string;
            name: string;
            url: string;
        };
        PagedModelRaceView: {
            content: components["schemas"]["RaceView"][];
            page: components["schemas"]["Page"];
        };
        RaceView: {
            abilityBonusOptions?: components["schemas"]["Choice"];
            abilityBonuses: components["schemas"]["AbilityBonus"][];
            age: string;
            alignment: string;
            index: string;
            languageDesc: string;
            languageOptions?: components["schemas"]["Choice"];
            languages: components["schemas"]["ApiReference"][];
            name: string;
            size: string;
            sizeDescription: string;
            /** Format: int64 */
            speed: number;
            startingProficiencies?: components["schemas"]["ApiReference"][];
            startingProficiencyOptions?: components["schemas"]["Choice"];
            subraces?: components["schemas"]["ApiReference"][];
            traits?: components["schemas"]["ApiReference"][];
            url: string;
        };
        PagedModelProficiencyView: {
            content: components["schemas"]["ProficiencyView"][];
            page: components["schemas"]["Page"];
        };
        ProficiencyView: {
            classes?: components["schemas"]["ApiReference"][];
            index: string;
            name: string;
            races?: components["schemas"]["ApiReference"][];
            reference: components["schemas"]["ApiReference"];
            type: string;
            url: string;
        };
        ActionUsage: {
            type: string;
            dice?: string;
            /** Format: int64 */
            minValue?: number;
        };
        Armor: WithRequired<components["schemas"]["MonsterArmorClass"], "type" | "value"> & {
            armor?: components["schemas"]["ApiReference"][];
        };
        Condition: WithRequired<components["schemas"]["MonsterArmorClass"], "type" | "value"> & {
            condition: components["schemas"]["ApiReference"];
        };
        Dex: WithRequired<components["schemas"]["MonsterArmorClass"], "type" | "value">;
        LegendaryAction: {
            name: string;
            desc: string;
            /** Format: int32 */
            attackBonus?: number;
            damage?: components["schemas"]["Damage"][];
            dc?: components["schemas"]["DifficultyClass"];
        };
        MonsterAction: {
            name: string;
            desc: string;
            /** Format: int64 */
            attackBonus?: number;
            damage?: components["schemas"]["Damage"][];
            dc?: components["schemas"]["DifficultyClass"];
            options?: components["schemas"]["Choice"];
            usage?: components["schemas"]["ActionUsage"];
            multiattackType?: string;
            actions?: components["schemas"]["ActionOption"][];
            actionOptions?: components["schemas"]["Choice"];
        };
        MonsterArmorClass: {
            /** Format: int32 */
            value: number;
            desc?: string;
            /** @enum {string} */
            type: "ARMOR" | "CONDITION" | "DEX" | "NATURAL" | "SPELL";
        };
        MonsterProficiency: {
            proficiency: components["schemas"]["ApiReference"];
            /** Format: int32 */
            value: number;
        };
        MonsterView: {
            actions?: components["schemas"]["MonsterAction"][];
            alignment: string;
            armorClass: (components["schemas"]["Armor"] | components["schemas"]["Condition"] | components["schemas"]["Dex"] | components["schemas"]["Natural"] | components["schemas"]["Spell"])[];
            /** Format: double */
            challengeRating: number;
            /** Format: int32 */
            charisma: number;
            conditionImmunities: components["schemas"]["ApiReference"][];
            /** Format: int32 */
            constitution: number;
            damageImmunities: string[];
            damageResistances: string[];
            damageVulnerabilities: string[];
            /** Format: int32 */
            dexterity: number;
            forms?: components["schemas"]["ApiReference"][];
            hitDice: string;
            /** Format: int32 */
            hitPoints: number;
            hitPointsRoll: string;
            image?: string;
            index: string;
            /** Format: int32 */
            intelligence: number;
            languages: string;
            legendaryActions?: components["schemas"]["LegendaryAction"][];
            name: string;
            proficiencies: components["schemas"]["MonsterProficiency"][];
            reactions?: components["schemas"]["Reaction"][];
            senses: components["schemas"]["Sense"];
            size: string;
            specialAbilities?: components["schemas"]["SpecialAbility"][];
            speed: components["schemas"]["Speed"];
            /** Format: int32 */
            strength: number;
            subtype?: string;
            type: string;
            url: string;
            /** Format: int32 */
            wisdom: number;
            /** Format: int64 */
            xp: number;
        };
        Natural: WithRequired<components["schemas"]["MonsterArmorClass"], "type" | "value">;
        PagedModelMonsterView: {
            content: components["schemas"]["MonsterView"][];
            page: components["schemas"]["Page"];
        };
        Reaction: {
            name: string;
            desc: string;
            dc?: components["schemas"]["DifficultyClass"];
        };
        Sense: {
            blindsight?: string;
            darkvision?: string;
            /** Format: int32 */
            passivePerception: number;
            tremorsense?: string;
            truesight?: string;
        };
        SpecialAbility: {
            name: string;
            desc: string;
            /** Format: int32 */
            attackBonus?: number;
            damage?: components["schemas"]["Damage"][];
            dc?: components["schemas"]["DifficultyClass"];
            spellcasting?: components["schemas"]["SpecialAbilitySpellcasting"];
            usage?: components["schemas"]["SpecialAbilityUsage"];
        };
        SpecialAbilitySpell: {
            name: string;
            /** Format: int32 */
            level: number;
            url: string;
            notes?: string;
            usage?: components["schemas"]["SpecialAbilityUsage"];
        };
        SpecialAbilitySpellcasting: {
            /** Format: int32 */
            level?: number;
            ability: components["schemas"]["ApiReference"];
            /** Format: int32 */
            dc?: number;
            /** Format: int32 */
            modifier?: number;
            componentsRequired: string[];
            school?: string;
            slots?: {
                [key: string]: number;
            };
            spells: components["schemas"]["SpecialAbilitySpell"][];
        };
        SpecialAbilityUsage: {
            type: string;
            /** Format: int32 */
            times?: number;
            restTypes?: string[];
        };
        Speed: {
            burrow?: string;
            climb?: string;
            fly?: string;
            hover?: boolean;
            swim?: string;
            walk?: string;
        };
        MagicSchoolView: {
            desc: string;
            index: string;
            name: string;
            url: string;
        };
        PagedModelMagicSchoolView: {
            content: components["schemas"]["MagicSchoolView"][];
            page: components["schemas"]["Page"];
        };
        MagicItemView: {
            desc: string[];
            equipmentCategory: components["schemas"]["ApiReference"];
            image?: string;
            index: string;
            name: string;
            rarity: components["schemas"]["Rarity"];
            url: string;
            variants: components["schemas"]["ApiReference"][];
            variant: boolean;
        };
        PagedModelMagicItemView: {
            content: components["schemas"]["MagicItemView"][];
            page: components["schemas"]["Page"];
        };
        Rarity: {
            name: string;
        };
        ClassSpecific: {
            /** Format: int32 */
            actionSurges?: number;
            /** Format: int32 */
            arcaneRecoveryLevels?: number;
            /** Format: int64 */
            auraRange?: number;
            /** Format: int32 */
            bardicInspirationDie?: number;
            /** Format: int32 */
            brutalCriticalDice?: number;
            /** Format: int32 */
            channelDivinityCharges?: number;
            creatingSpellSlots?: components["schemas"]["ClassSpecificCreatingSpellSlot"][];
            /** Format: int32 */
            destroyUndeadCr?: number;
            /** Format: int32 */
            extraAttacks?: number;
            /** Format: int32 */
            favoredEnemies?: number;
            /** Format: int32 */
            favoredTerrain?: number;
            /** Format: int32 */
            indomitableUses?: number;
            /** Format: int32 */
            invocationsKnown?: number;
            /** Format: int32 */
            kiPoints?: number;
            /** Format: int32 */
            magicalSecretsMax5?: number;
            /** Format: int32 */
            magicalSecretsMax7?: number;
            /** Format: int32 */
            magicalSecretsMax9?: number;
            martialArts?: components["schemas"]["ClassSpecificMartialArt"];
            /** Format: int32 */
            metamagicKnown?: number;
            /** Format: int32 */
            mysticArcanumLevel6?: number;
            /** Format: int32 */
            mysticArcanumLevel7?: number;
            /** Format: int32 */
            mysticArcanumLevel8?: number;
            /** Format: int32 */
            mysticArcanumLevel9?: number;
            /** Format: int32 */
            rageCount?: number;
            /** Format: int32 */
            rageDamageBonus?: number;
            sneakAttack?: components["schemas"]["ClassSpecificSneakAttack"];
            /** Format: int32 */
            songOfRestDie?: number;
            /** Format: int32 */
            sorceryPoints?: number;
            /** Format: int64 */
            unarmoredMovement?: number;
            wildShapeFly?: boolean;
            /** Format: int32 */
            wildShapeMaxCr?: number;
            wildShapeSwim?: boolean;
        };
        ClassSpecificCreatingSpellSlot: {
            /** Format: int32 */
            sorceryPointCost: number;
            /** Format: int32 */
            spellSlotLevel: number;
        };
        ClassSpecificMartialArt: {
            /** Format: int32 */
            diceCount: number;
            /** Format: int32 */
            diceValue: number;
        };
        ClassSpecificSneakAttack: {
            /** Format: int32 */
            diceCount: number;
            /** Format: int32 */
            diceValue: number;
        };
        LevelView: {
            /** Format: int64 */
            abilityScoreBonuses?: number;
            class: components["schemas"]["ApiReference"];
            classSpecific?: components["schemas"]["ClassSpecific"];
            features: components["schemas"]["ApiReference"][];
            index: string;
            /** Format: int32 */
            level: number;
            /** Format: int32 */
            profBonus?: number;
            spellcasting?: components["schemas"]["SpellcastingSlots"];
            subclass?: components["schemas"]["ApiReference"];
            subclassSpecific?: components["schemas"]["SubclassSpecific"];
            url: string;
        };
        PagedModelLevelView: {
            content: components["schemas"]["LevelView"][];
            page: components["schemas"]["Page"];
        };
        SpellcastingSlots: {
            /** Format: int32 */
            cantripsKnown?: number;
            /** Format: int32 */
            spellSlotsLevel1?: number;
            /** Format: int32 */
            spellSlotsLevel2?: number;
            /** Format: int32 */
            spellSlotsLevel3?: number;
            /** Format: int32 */
            spellSlotsLevel4?: number;
            /** Format: int32 */
            spellSlotsLevel5?: number;
            /** Format: int32 */
            spellSlotsLevel6?: number;
            /** Format: int32 */
            spellSlotsLevel7?: number;
            /** Format: int32 */
            spellSlotsLevel8?: number;
            /** Format: int32 */
            spellSlotsLevel9?: number;
            /** Format: int32 */
            spellsKnown?: number;
        };
        SubclassSpecific: {
            /** Format: int32 */
            additionalMagicalSecretsMaxLvl?: number;
            /** Format: int64 */
            auraRange?: number;
        };
        LanguageView: {
            desc?: string;
            index: string;
            name: string;
            script?: string;
            type: string;
            typicalSpeakers: string[];
            url: string;
        };
        PagedModelLanguageView: {
            content: components["schemas"]["LanguageView"][];
            page: components["schemas"]["Page"];
        };
        FeatureSpecific: {
            subfeatureOptions?: components["schemas"]["Choice"];
            expertiseOptions?: components["schemas"]["Choice"];
            invocations?: components["schemas"]["ApiReference"][];
        };
        FeatureView: {
            characterClass: components["schemas"]["ApiReference"];
            desc: string[];
            parent?: components["schemas"]["ApiReference"];
            index: string;
            /** Format: int32 */
            level: number;
            name: string;
            prerequisite?: (components["schemas"]["FeaturePrerequisite"] | components["schemas"]["LevelPrerequisite"] | components["schemas"]["ProficiencyPrerequisite"] | components["schemas"]["SpellPrerequisite"])[];
            reference?: string;
            subclass?: components["schemas"]["ApiReference"];
            featureSpecific?: components["schemas"]["FeatureSpecific"];
            url: string;
        };
        PagedModelFeatureView: {
            content: components["schemas"]["FeatureView"][];
            page: components["schemas"]["Page"];
        };
        FeatPrerequisite: {
            abilityScore: components["schemas"]["ApiReference"];
            /** Format: int32 */
            minimumScore: number;
        };
        FeatView: {
            index: string;
            name: string;
            prerequisites: components["schemas"]["FeatPrerequisite"][];
            desc: string[];
            url: string;
        };
        PagedModelFeatView: {
            content: components["schemas"]["FeatView"][];
            page: components["schemas"]["Page"];
        };
        ArmorClass: {
            /** Format: int32 */
            base: number;
            dexBonus: boolean;
            /** Format: int32 */
            maxBonus?: number;
        };
        Content: {
            item: components["schemas"]["ApiReference"];
            /** Format: int32 */
            quantity: number;
        };
        Cost: {
            /** Format: int32 */
            quantity: number;
            unit: string;
        };
        EquipmentView: {
            armorCategory?: string;
            armorClass?: components["schemas"]["ArmorClass"];
            capacity?: string;
            categoryRange?: string;
            contents?: components["schemas"]["Content"][];
            cost: components["schemas"]["Cost"];
            damage?: components["schemas"]["Damage"];
            desc?: string;
            equipmentCategory: components["schemas"]["ApiReference"];
            gearCategory?: components["schemas"]["ApiReference"];
            index: string;
            name: string;
            properties?: components["schemas"]["ApiReference"][];
            /** Format: int32 */
            quantity?: number;
            range?: components["schemas"]["Range"];
            special?: string[];
            speed?: components["schemas"]["Speed"];
            stealthDisadvantage?: boolean;
            /** Format: int32 */
            strMinimum?: number;
            throwRange?: components["schemas"]["ThrowRange"];
            toolCategory?: string;
            twoHandedDamage?: components["schemas"]["TwoHandedDamage"];
            vehicleCategory?: string;
            weaponCategory?: string;
            weaponRange?: string;
            /** Format: double */
            weight?: number;
            url: string;
        };
        PagedModelEquipmentView: {
            content: components["schemas"]["EquipmentView"][];
            page: components["schemas"]["Page"];
        };
        Range: {
            /** Format: int32 */
            long?: number;
            /** Format: int32 */
            normal: number;
        };
        ThrowRange: {
            /** Format: int32 */
            long: number;
            /** Format: int32 */
            normal: number;
        };
        TwoHandedDamage: {
            damageDice: string;
            damageType: components["schemas"]["ApiReference"];
        };
        EquipmentCategoryView: {
            equipment: components["schemas"]["ApiReference"][];
            index: string;
            name: string;
            url: string;
        };
        PagedModelEquipmentCategoryView: {
            content: components["schemas"]["EquipmentCategoryView"][];
            page: components["schemas"]["Page"];
        };
        DamageTypeView: {
            index: string;
            name: string;
            desc: string[];
            url: string;
        };
        PagedModelDamageTypeView: {
            content: components["schemas"]["DamageTypeView"][];
            page: components["schemas"]["Page"];
        };
        ConditionView: {
            index: string;
            name: string;
            desc: string[];
            url: string;
        };
        PagedModelConditionView: {
            content: components["schemas"]["ConditionView"][];
            page: components["schemas"]["Page"];
        };
        CharacterClassView: {
            classLevels?: string;
            /** Format: int32 */
            hitDie?: number;
            index?: string;
            name?: string;
            proficiencies?: components["schemas"]["ApiReference"][];
            proficiencyChoices?: components["schemas"]["Choice"][];
            savingThrows?: components["schemas"]["ApiReference"][];
            spellcasting?: components["schemas"]["Spellcasting"];
            spells?: string;
            startingEquipment?: components["schemas"]["EquipmentQuantity"][];
            startingEquipmentOptions?: components["schemas"]["Choice"][];
            multiClassing?: components["schemas"]["MultiClassing"];
            subclasses?: components["schemas"]["ApiReference"][];
            url?: string;
        };
        EquipmentQuantity: {
            equipment: components["schemas"]["ApiReference"];
            /** Format: int32 */
            quantity: number;
        };
        MultiClassing: {
            prerequisites?: components["schemas"]["MultiClassingPrerequisite"][];
            prerequisiteOptions?: components["schemas"]["Choice"];
            proficiencies?: components["schemas"]["ApiReference"][];
            proficiencyChoices?: components["schemas"]["Choice"][];
        };
        MultiClassingPrerequisite: {
            abilityScore: components["schemas"]["ApiReference"];
            /** Format: int32 */
            minimumScore: number;
        };
        PagedModelCharacterClassView: {
            content: components["schemas"]["CharacterClassView"][];
            page: components["schemas"]["Page"];
        };
        Spellcasting: {
            info: components["schemas"]["SpellcastingInfo"][];
            /** Format: int32 */
            level: number;
            spellcastingAbility: components["schemas"]["ApiReference"];
        };
        SpellcastingInfo: {
            desc: string[];
            name: string;
        };
        BackgroundView: {
            index: string;
            name?: string;
            startingProficiencies?: components["schemas"]["ApiReference"][];
            languageOptions?: components["schemas"]["Choice"];
            startingEquipment?: components["schemas"]["StartingEquipment"][];
            startingEquipmentOptions?: components["schemas"]["Choice"][];
            feature?: components["schemas"]["Feature"];
            personalityTraits?: components["schemas"]["Choice"];
            ideals?: components["schemas"]["Choice"];
            bonds?: components["schemas"]["Choice"];
            flaws?: components["schemas"]["Choice"];
            url?: string;
        };
        Feature: {
            name: string;
            desc: string[];
        };
        PagedModelBackgroundView: {
            content: components["schemas"]["BackgroundView"][];
            page: components["schemas"]["Page"];
        };
        StartingEquipment: {
            equipment: components["schemas"]["ApiReference"];
            /** Format: int32 */
            quantity: number;
        };
        AlignmentView: {
            index: string;
            name?: string;
            abbreviation?: string;
            desc?: string;
            url?: string;
        };
        PagedModelAlignmentView: {
            content: components["schemas"]["AlignmentView"][];
            page: components["schemas"]["Page"];
        };
        AbilityScoreView: {
            desc?: string[];
            fullName?: string;
            index?: string;
            name?: string;
            skills?: components["schemas"]["ApiReference"][];
            url?: string;
        };
        PagedModelAbilityScoreView: {
            content: components["schemas"]["AbilityScoreView"][];
            page: components["schemas"]["Page"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getWeaponProperties: {
        parameters: {
            query?: {
                /** @description Zero-based page index (0..N) */
                page?: number;
                /** @description The size of the page to be returned */
                size?: number;
                /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
                sort?: string[];
                name?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PagedModelWeaponPropertyView"];
                };
            };
        };
    };
    getWeaponProperty: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                index: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WeaponPropertyView"];
                };
            };
        };
    };
    getTraits: {
        parameters: {
            query?: {
                /** @description Zero-based page index (0..N) */
                page?: number;
                /** @description The size of the page to be returned */
                size?: number;
                /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
                sort?: string[];
                name?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PagedModelTraitView"];
                };
            };
        };
    };
    getTrait: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                index: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TraitView"];
                };
            };
        };
    };
    getSubraces: {
        parameters: {
            query?: {
                /** @description Zero-based page index (0..N) */
                page?: number;
                /** @description The size of the page to be returned */
                size?: number;
                /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
                sort?: string[];
                name?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PagedModelSubraceView"];
                };
            };
        };
    };
    getSubrace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                index: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SubraceView"];
                };
            };
        };
    };
    getSubclasses: {
        parameters: {
            query?: {
                /** @description Zero-based page index (0..N) */
                page?: number;
                /** @description The size of the page to be returned */
                size?: number;
                /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
                sort?: string[];
                name?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PagedModelSubclassView"];
                };
            };
        };
    };
    getSubclass: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                index: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SubclassView"];
                };
            };
        };
    };
    getSpells: {
        parameters: {
            query?: {
                /** @description Zero-based page index (0..N) */
                page?: number;
                /** @description The size of the page to be returned */
                size?: number;
                /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
                sort?: string[];
                name?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PagedModelSpellView"];
                };
            };
        };
    };
    getSpell: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                index: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SpellView"];
                };
            };
        };
    };
    getSkills: {
        parameters: {
            query?: {
                /** @description Zero-based page index (0..N) */
                page?: number;
                /** @description The size of the page to be returned */
                size?: number;
                /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
                sort?: string[];
                name?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PagedModelSkillView"];
                };
            };
        };
    };
    getSkill: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                index: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SkillView"];
                };
            };
        };
    };
    getRules: {
        parameters: {
            query?: {
                /** @description Zero-based page index (0..N) */
                page?: number;
                /** @description The size of the page to be returned */
                size?: number;
                /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
                sort?: string[];
                name?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PagedModelRuleView"];
                };
            };
        };
    };
    getRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                index: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RuleView"];
                };
            };
        };
    };
    getRuleSections: {
        parameters: {
            query?: {
                /** @description Zero-based page index (0..N) */
                page?: number;
                /** @description The size of the page to be returned */
                size?: number;
                /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
                sort?: string[];
                name?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PagedModelRuleSectionView"];
                };
            };
        };
    };
    getRuleSection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                index: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RuleSectionView"];
                };
            };
        };
    };
    getRaces: {
        parameters: {
            query?: {
                /** @description Zero-based page index (0..N) */
                page?: number;
                /** @description The size of the page to be returned */
                size?: number;
                /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
                sort?: string[];
                name?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PagedModelRaceView"];
                };
            };
        };
    };
    getRace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                index: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RaceView"];
                };
            };
        };
    };
    getProficiencies: {
        parameters: {
            query?: {
                /** @description Zero-based page index (0..N) */
                page?: number;
                /** @description The size of the page to be returned */
                size?: number;
                /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
                sort?: string[];
                name?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PagedModelProficiencyView"];
                };
            };
        };
    };
    getProficiency: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                index: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProficiencyView"];
                };
            };
        };
    };
    getMonsters: {
        parameters: {
            query?: {
                /** @description Zero-based page index (0..N) */
                page?: number;
                /** @description The size of the page to be returned */
                size?: number;
                /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
                sort?: string[];
                name?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PagedModelMonsterView"];
                };
            };
        };
    };
    getMonster: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                index: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MonsterView"];
                };
            };
        };
    };
    getMagicSchools: {
        parameters: {
            query?: {
                /** @description Zero-based page index (0..N) */
                page?: number;
                /** @description The size of the page to be returned */
                size?: number;
                /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
                sort?: string[];
                name?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PagedModelMagicSchoolView"];
                };
            };
        };
    };
    getMagicSchool: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                index: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MagicSchoolView"];
                };
            };
        };
    };
    getMagicItems: {
        parameters: {
            query?: {
                /** @description Zero-based page index (0..N) */
                page?: number;
                /** @description The size of the page to be returned */
                size?: number;
                /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
                sort?: string[];
                name?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PagedModelMagicItemView"];
                };
            };
        };
    };
    getMagicItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                index: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MagicItemView"];
                };
            };
        };
    };
    getLevels: {
        parameters: {
            query?: {
                /** @description Zero-based page index (0..N) */
                page?: number;
                /** @description The size of the page to be returned */
                size?: number;
                /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
                sort?: string[];
                level?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PagedModelLevelView"];
                };
            };
        };
    };
    getLevel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                index: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LevelView"];
                };
            };
        };
    };
    getLanguages: {
        parameters: {
            query?: {
                /** @description Zero-based page index (0..N) */
                page?: number;
                /** @description The size of the page to be returned */
                size?: number;
                /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
                sort?: string[];
                name?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PagedModelLanguageView"];
                };
            };
        };
    };
    getLanguage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                index: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LanguageView"];
                };
            };
        };
    };
    getFeatures: {
        parameters: {
            query?: {
                /** @description Zero-based page index (0..N) */
                page?: number;
                /** @description The size of the page to be returned */
                size?: number;
                /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
                sort?: string[];
                name?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PagedModelFeatureView"];
                };
            };
        };
    };
    getFeature: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                index: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FeatureView"];
                };
            };
        };
    };
    getFeats: {
        parameters: {
            query?: {
                /** @description Zero-based page index (0..N) */
                page?: number;
                /** @description The size of the page to be returned */
                size?: number;
                /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
                sort?: string[];
                name?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PagedModelFeatView"];
                };
            };
        };
    };
    getFeat: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                index: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FeatView"];
                };
            };
        };
    };
    getAllEquipment: {
        parameters: {
            query?: {
                /** @description Zero-based page index (0..N) */
                page?: number;
                /** @description The size of the page to be returned */
                size?: number;
                /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
                sort?: string[];
                name?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PagedModelEquipmentView"];
                };
            };
        };
    };
    getEquipment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                index: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EquipmentView"];
                };
            };
        };
    };
    getEquipmentCategories: {
        parameters: {
            query?: {
                /** @description Zero-based page index (0..N) */
                page?: number;
                /** @description The size of the page to be returned */
                size?: number;
                /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
                sort?: string[];
                name?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PagedModelEquipmentCategoryView"];
                };
            };
        };
    };
    getEquipmentCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                index: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EquipmentCategoryView"];
                };
            };
        };
    };
    getDamageTypes: {
        parameters: {
            query?: {
                /** @description Zero-based page index (0..N) */
                page?: number;
                /** @description The size of the page to be returned */
                size?: number;
                /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
                sort?: string[];
                name?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PagedModelDamageTypeView"];
                };
            };
        };
    };
    getDamageType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                index: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DamageTypeView"];
                };
            };
        };
    };
    getConditions: {
        parameters: {
            query?: {
                /** @description Zero-based page index (0..N) */
                page?: number;
                /** @description The size of the page to be returned */
                size?: number;
                /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
                sort?: string[];
                name?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PagedModelConditionView"];
                };
            };
        };
    };
    getCondition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                index: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ConditionView"];
                };
            };
        };
    };
    getClasses: {
        parameters: {
            query?: {
                /** @description Zero-based page index (0..N) */
                page?: number;
                /** @description The size of the page to be returned */
                size?: number;
                /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
                sort?: string[];
                name?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PagedModelCharacterClassView"];
                };
            };
        };
    };
    getCharacterClass: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                index: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CharacterClassView"];
                };
            };
        };
    };
    getBackgrounds: {
        parameters: {
            query?: {
                /** @description Zero-based page index (0..N) */
                page?: number;
                /** @description The size of the page to be returned */
                size?: number;
                /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
                sort?: string[];
                name?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PagedModelBackgroundView"];
                };
            };
        };
    };
    getBackground: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                index: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BackgroundView"];
                };
            };
        };
    };
    getAlignments: {
        parameters: {
            query?: {
                /** @description Zero-based page index (0..N) */
                page?: number;
                /** @description The size of the page to be returned */
                size?: number;
                /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
                sort?: string[];
                name?: string;
                abbreviation?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PagedModelAlignmentView"];
                };
            };
        };
    };
    getAlignment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                index: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AlignmentView"];
                };
            };
        };
    };
    getAbilityScores: {
        parameters: {
            query?: {
                /** @description Zero-based page index (0..N) */
                page?: number;
                /** @description The size of the page to be returned */
                size?: number;
                /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
                sort?: string[];
                name?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PagedModelAbilityScoreView"];
                };
            };
        };
    };
    getAbilityScore: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                index: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AbilityScoreView"];
                };
            };
        };
    };
}
type WithRequired<T, K extends keyof T> = T & {
    [P in K]-?: T[P];
};
